name: Store MSIX Download and Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  download-and-release-msix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull App Packages for CmdPal Extension
        uses: sht2017/Pull-Microsoft-Store@main
        id: store_download
        with:
          product-id: '9PPNTDCD5S8Z'
          output-path: './app-packages'

      - name: Verify Download
        if: steps.store_download.outcome == 'success'
        run: |
          echo "Successfully downloaded packages:"
          ls -R ./app-packages

      - name: Handle Failure
        if: steps.store_download.outcome != 'success'
        run: echo "Download failed."

      - name: Upload MSIX as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CmdPal-MSIX
          path: ./app-packages/*.msix

      - name: Upload MSIX to GitHub Release
        if: github.event_name == 'release'
        uses: JasonWei512/Upload-Microsoft-Store-MSIX-Package-to-GitHub-Release@v1
        with:
          store-id: '9PPNTDCD5S8Z'
          token: ${{ secrets.GITHUB_TOKEN }} # you do not need to manually set up secrets.GITHUB_TOKEN in your repo, GitHub Automatically Provides It
          asset-name-pattern: CmdPal_{version}_{arch}